---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authorize":
    get:
      summary: authorize session
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: http://localhost:3000
