---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authorize":
    get:
      summary: authorize session
      tags:
      - Sessions
      responses:
        '200':
          description: Successful
  "/auths/{provider}/callback":
    parameters:
    - name: provider
      in: path
      description: provider
      required: true
      schema:
        type: string
    - name: state
      in: query
      required: true
      schema:
        type: string
    - name: code
      in: query
      required: true
      schema:
        type: string
    get:
      summary: callback session
      tags:
      - Sessions
      responses:
        '200':
          description: Successful
        '422':
          description: Unprocessable Entity
  "/tweets":
    post:
      summary: create tweets
      tags:
      - Tweets
      parameters:
      - name: token
        in: query
        required: true
        schema:
          type: string
      - name: location
        in: query
        schema:
          type: object
          properties:
            location:
              type: object
              properties:
                lat:
                  type: number
                  example: 76.2592
                lon:
                  type: number
                  example: -157.93604
                name:
                  type: string
                  example: City Name
      responses:
        '200':
          description: Successful
        '404':
          description: Token Not Found
        '422':
          description: Unprocessable Entity
servers:
- url: http://localhost:3000
