---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authorize":
    get:
      summary: authorize session
      tags:
      - Sessions
      responses:
        '200':
          description: Successful
  "/auths/{provider}/callback":
    parameters:
    - name: provider
      in: path
      description: provider
      required: true
      schema:
        type: string
    - name: state
      in: query
      required: true
      schema:
        type: string
    - name: code
      in: query
      required: true
      schema:
        type: string
    get:
      summary: callback session
      tags:
      - Sessions
      responses:
        '200':
          description: Successful
        '422':
          description: Unprocessable Entity
  "/tweets":
    get:
      summary: index tweets
      tags:
      - Tweets
      security:
      - bearer_auth: []
        api_key: []
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
    post:
      summary: create tweets
      tags:
      - Tweets
      security:
      - bearer_auth: []
        api_key: []
      parameters:
      - name: location
        in: query
        schema:
          type: object
          properties:
            location:
              type: object
              properties:
                lat:
                  type: number
                  example: 76.2592
                lon:
                  type: number
                  example: -157.93604
                name:
                  type: string
                  example: City Name
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity
servers:
- url: http://localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
    api_key:
      type: apiKey
      name: api_key
      in: query
