# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  <<: *default
  port: <%= ENV["DATABASE_PORT"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *local
  database: owm_bot_api_development

test:
  <<: *local
  database: owm_bot_api_test

production:
  <<: *default
  database: owm_bot_api_production
  username: <%= ENV["DATABASE_USERNAME_PROD"] %>
  password: <%= ENV["DATABASE_PASSWORD_PROD"] %>
